name: "My First Pipeline"

on:
  push:
    branches:
    - main

jobs:
  Pipeline-Job:
    name: 'My First Pipeline Job'
    runs-on: ubuntu-latest
    
    env:
      working-directory: .
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      
    - name: Build Docker Container
      run: |
         sudo docker build . -t michaelbraunbass/badwebapp
         
    - name: Smoke Test
      run: |
         sudo docker run --rm -d -p 8080:8080 michaelbraunbass/badwebapp
         curl localhost:8080
         
    