name: "My First Pipeline"

on:
  push:
    branches:
    - openshift

jobs:
  Pipeline-Job:
    name: 'My First Pipeline Job'
    runs-on: ubuntu-latest
    env:
      CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
      CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        ref: openshift

    - name: ShiftLeft Web Application Code Scan
      run: |
            chmod +x shiftleft
            ./shiftleft code-scan -s .
      continue-on-error: true    
      
    - name: Build Docker Container
      run: |
         sudo docker build . -t michaelbraunbass/badwebapp
         
    - name: Smoke Test
      run: |
         sudo docker run -d -p 8080:8080 michaelbraunbass/badwebapp
         sleep 4
         curl localhost:8080
    
    - name: Shift Left Container Scan
      run: |
        docker save michaelbraunbass/badwebapp -o badwebapp.tar
        ./shiftleft image-scan -t 1800 -i ./badwebapp.tar
      continue-on-error: true
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
             
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: michaelbraunbass/testbadapp:openshift
        
         
