name: "My First Pipeline"

on:
  push:
    branches:
    - main

jobs:
  Pipeline-Job:
    name: 'My First Pipeline Job'
    runs-on: ubuntu-latest
    
    env:
      working-directory: .
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      
    - name: Build Docker Container
      run: |
         sudo docker build . -t michaelbraunbass/badwebapp
         
    - name: Smoke Test
      run: |
         sudo docker run --rm -d -p 8080:8080 michaelbraunbass/badwebapp
         sleep 4
         curl localhost:8080
         
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
          repository: michaelbraunbass/testbadapp
          tag_with_ref: true