name: "My First Pipeline"

on:
  push:
    branches:
    - main

jobs:
  Pipeline-Job:
    name: 'My First Pipeline Job'
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      
    - name: Build Docker Container
      run: |
         sudo docker build . -t michaelbraunbass/badwebapp
         
    - name: Smoke Test
      run: |
         sudo docker run -d -p 8080:8080 michaelbraunbass/badwebapp
         sleep 4
         curl localhost:8080
         
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: michaelbraunbass/testbadapp:latest